using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UniversalWeahterForecast.EntityLayer.Entitys;

namespace UniversalWeahterForecast.DataAccessLayer.DBOperations
{
    public class DataGenerator
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new UniversalWeatherForecastDbContext(serviceProvider.GetRequiredService<DbContextOptions<UniversalWeatherForecastDbContext>>()))
            {
                if (context.WeatherForecasts.Any())
                {
                    return;
                }
                Random rnd = new();

                context.CelestalBodies.AddRange(
                        new CelestalBody { Name = "Celestria", 	    WhoseSatellite = 0}, //1 //1+
                        new CelestalBody { Name = "Stellara",       WhoseSatellite = 0}, //2 //1
                        new CelestalBody { Name = "Cosmirova", 	    WhoseSatellite = 0}, //3 //2+
                        new CelestalBody { Name = "Galaxara", 		WhoseSatellite = 0}, //4 //2+
                        new CelestalBody { Name = "Lunatria", 		WhoseSatellite = 0}, //5 //1
                        new CelestalBody { Name = "Nebulonia",      WhoseSatellite = 0}, //6 //1
                        new CelestalBody { Name = "Astrionyx",  	WhoseSatellite = 1},
                        new CelestalBody { Name = "Galactrix",  	WhoseSatellite = 4},
                        new CelestalBody { Name = "Quasarion", 	    WhoseSatellite = 3},
                        new CelestalBody { Name = "Novaflare", 	    WhoseSatellite = 2},
                        new CelestalBody { Name = "Astrolynx", 	    WhoseSatellite = 4},
                        new CelestalBody { Name = "Orionex", 		WhoseSatellite = 3},
                        new CelestalBody { Name = "Astralspire", 	WhoseSatellite = 5},
                        new CelestalBody { Name = "Nebulique", 	    WhoseSatellite = 6}
                    );

                context.WeatherTypes.AddRange(
                        new WeatherType { Name = "Güneşli" },
                        new WeatherType { Name = "Parçalı Bulutlu" },
                        new WeatherType { Name = "Kapalı" },
                        new WeatherType { Name = "Yağışlı" },
                        new WeatherType { Name = "Sağnak Yağışlı" },
                        new WeatherType { Name = "Fırtına" }
                    );
                context.WeatherForecasts.AddRange(
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) }
                    );
                context.SaveChanges();
            }
        }
    }
}
