using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UniversalWeahterForecast.EntityLayer.Entitys;

namespace UniversalWeahterForecast.DataAccessLayer.DBOperations
{
    public class DataGenerator
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new UniversalWeatherForecastDbContext(serviceProvider.GetRequiredService<DbContextOptions<UniversalWeatherForecastDbContext>>()))
            {
                if (context.WeatherForecasts.Any())
                {
                    return;
                }
                Random rnd = new();

                context.CelestalBodies.AddRange(
                        new CelestalBody { Name = "Luminara", 		IsPlanet = true },
                        new CelestalBody { Name = "Celestria", 	    IsPlanet = true },
                        new CelestalBody { Name = "Nebulonova", 	IsPlanet = true },
                        new CelestalBody { Name = "Astrionyx",  	IsPlanet = false },
                        new CelestalBody { Name = "Galactrix",  	IsPlanet = true },
                        new CelestalBody { Name = "Stellara", 		IsPlanet = true },
                        new CelestalBody { Name = "Quasarion", 	    IsPlanet = true },
                        new CelestalBody { Name = "Novaflare", 	    IsPlanet = true },
                        new CelestalBody { Name = "Astrolynx", 	    IsPlanet = false },
                        new CelestalBody { Name = "Cosmirova", 	    IsPlanet = true },
                        new CelestalBody { Name = "Orionex", 		IsPlanet = true },
                        new CelestalBody { Name = "Astralspire", 	IsPlanet = true },
                        new CelestalBody { Name = "Nebulique", 	    IsPlanet = true },
                        new CelestalBody { Name = "Stellarion", 	IsPlanet = false },
                        new CelestalBody { Name = "Galaxara", 		IsPlanet = true },
                        new CelestalBody { Name = "Lunatrix", 		IsPlanet = true },
                        new CelestalBody { Name = "Solarionis", 	IsPlanet = true },
                        new CelestalBody { Name = "Celestialis", 	IsPlanet = false },
                        new CelestalBody { Name = "Astronique", 	IsPlanet = false },
                        new CelestalBody { Name = "Nebuliqueon", 	IsPlanet = false },
                        new CelestalBody { Name = "Cometrix", 		IsPlanet = true },
                        new CelestalBody { Name = "Starblaze", 	    IsPlanet = true },
                        new CelestalBody { Name = "Lunarisphere", 	IsPlanet = true },
                        new CelestalBody { Name = "Solarflareon", 	IsPlanet = false },
                        new CelestalBody { Name = "Nebulonia",      IsPlanet = true }
                    );

                context.WeatherTypes.AddRange(
                        new WeatherType { Name = "Güneşli" },
                        new WeatherType { Name = "Parçalı Bulutlu" },
                        new WeatherType { Name = "Kapalı" },
                        new WeatherType { Name = "Yağışlı" },
                        new WeatherType { Name = "Sağnak Yağışlı" },
                        new WeatherType { Name = "Fırtına" }
                    );
                context.WeatherForecasts.AddRange(
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 1,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 2,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 3,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 4,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 5,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 6,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 7,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 8,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 9,  TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 10, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 11, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 12, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 13, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 14, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 15, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 16, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 17, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 18, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 19, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 20, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 21, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 22, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 23, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 24, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { BodyId = 25, TypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) }
                    );
                context.SaveChanges();
            }
        }
    }
}
