using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UniversalWeahterForecast.EntityLayer.Entitys;

namespace UniversalWeahterForecast.DataAccessLayer.DBOperations
{
    public class DataGenerator
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new UniversalWeatherForecastDbContext(serviceProvider.GetRequiredService<DbContextOptions<UniversalWeatherForecastDbContext>>()))
            {
                if (context.WeatherForecasts.Any())
                {
                    return;
                }
                Random rnd = new();

                context.CelestalBodies.AddRange(
                        new CelestalBody { Name = "Luminara", 		IsPlanet = true },
                        new CelestalBody { Name = "Celestria", 	    IsPlanet = true },
                        new CelestalBody { Name = "Nebulonova", 	IsPlanet = true },
                        new CelestalBody { Name = "Astrionyx",  	IsPlanet = false },
                        new CelestalBody { Name = "Galactrix",  	IsPlanet = true },
                        new CelestalBody { Name = "Stellara", 		IsPlanet = true },
                        new CelestalBody { Name = "Quasarion", 	    IsPlanet = true },
                        new CelestalBody { Name = "Novaflare", 	    IsPlanet = true },
                        new CelestalBody { Name = "Astrolynx", 	    IsPlanet = false },
                        new CelestalBody { Name = "Cosmirova", 	    IsPlanet = true },
                        new CelestalBody { Name = "Orionex", 		IsPlanet = true },
                        new CelestalBody { Name = "Astralspire", 	IsPlanet = true },
                        new CelestalBody { Name = "Nebulique", 	    IsPlanet = true },
                        new CelestalBody { Name = "Stellarion", 	IsPlanet = false },
                        new CelestalBody { Name = "Galaxara", 		IsPlanet = true },
                        new CelestalBody { Name = "Lunatrix", 		IsPlanet = true },
                        new CelestalBody { Name = "Solarionis", 	IsPlanet = true },
                        new CelestalBody { Name = "Celestialis", 	IsPlanet = false },
                        new CelestalBody { Name = "Astronique", 	IsPlanet = false },
                        new CelestalBody { Name = "Nebuliqueon", 	IsPlanet = false },
                        new CelestalBody { Name = "Cometrix", 		IsPlanet = true },
                        new CelestalBody { Name = "Starblaze", 	    IsPlanet = true },
                        new CelestalBody { Name = "Lunarisphere", 	IsPlanet = true },
                        new CelestalBody { Name = "Solarflareon", 	IsPlanet = false },
                        new CelestalBody { Name = "Nebulonia",      IsPlanet = true }
                    );

                context.WeatherTypes.AddRange(
                        new WeatherType { Name = "Güneşli" },
                        new WeatherType { Name = "Parçalı Bulutlu" },
                        new WeatherType { Name = "Kapalı" },
                        new WeatherType { Name = "Yağışlı" },
                        new WeatherType { Name = "Sağnak Yağışlı" },
                        new WeatherType { Name = "Fırtına" }
                    );
                context.WeatherForecasts.AddRange(
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 1, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 2, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 3, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 4, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 5, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 6, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 7, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 8, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 9, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 10, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 11, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 12, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 13, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 14, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 15, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 16, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 17, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 18, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 19, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 20, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 21, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 22, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 23, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 24, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(1) },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(2) },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(3) },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(4) },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(5) },
                        new WeatherForecast { CelestialBodyId = 25, WeatherTypeId = rnd.Next(1, 7), Temprature = rnd.Next(5, 30), WeatherTime = DateTime.Now.AddDays(6) }
                    );
                context.SaveChanges();
            }
        }
    }
}
