env:
  DOTNET_VERSION: '7.0.x' 

on:
  push:
    branches: ["main"]
  workflow_dispatch:

name: 🎉 Build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: .Net Core Kurulumu
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Derleme öncesi Bağımlılık Önbelleğini Ayarlama
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: .Net Core ile Build Et
        run: dotnet build --configuration Release

